project:
  name: cloudformation-base-eks
  owner: quickstart-eng@amazon.com
  shorten_stack_name: true
  regions:
    - us-east-1
  template: templates/amazon-eks-entrypoint-new-vpc.template.yaml
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  package_lambda: true
  build_submodules: true
tests:
  defaults:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      NodeGroupType: Unmanaged
      LoadBalancerController: Disabled
      ProvisionBastionHost: Disabled
      ClusterAutoScaler: Enabled
      QSS3BucketName: $[taskcat_autobucket]
      s3_bucket: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    regions:
      - us-east-1
