AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWSQS-EKS-Cluster  resource type

Globals:
  Function:
    Timeout: 180000  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cmd.main::handleRequest
      Runtime: provided.al2023
      CodeUri: /home/prbhle/cloudformation-base-eks/awsqs-eks-cluster.zip
  TestEntrypoint:
     Type: AWS::Serverless::Function
     Properties:
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: /home/prbhle/cloudformation-base-eks/output/build/functions/packages/EksClusterResource
